exports.dropsTemplate = (
  drops
) => `// Generated by dev/serverImport. Do not edit manually.
import { items } from "./items";
import { Drop } from "../../state/Drop";

export const drops: Record<string, Drop[]> = ${itemReferences(
  JSON.stringify(drops, null, 2)
)};
`;

const itemReferences = (jsonString) =>
  jsonString.replace(/"item": (\d+)/g, (match, id) => `"item": items[${id}]`);
