exports.itemsTemplate = (
  items
) => `// Generated by dev/serverImport. Do not edit manually.
import { ItemId } from "../../state/ItemId";

export const items = ${addAsItemId(JSON.stringify(groupById(items), null, 2))};
`;

const groupById = (items) =>
  items.reduce((group, item) => ({ ...group, [item.id]: item }), {});

const addAsItemId = (jsonString) =>
  jsonString.replace(/"id": (\d+)/g, (match, id) => `"id": ${id} as ItemId`);
